//go:build linux && cgo && !agent

package cluster

// Generated by dbgen - DO NOT EDIT

// TableName returns the table name for [AuthGroupsRow] entities.
func (a AuthGroupsRow) TableName() string {
	return "auth_groups"
}

// SelectColumns returns a slice of column names for [AuthGroupsRow] entities.
func (a AuthGroupsRow) SelectColumns() []string {
	return []string{
		"auth_groups.id",
		"auth_groups.name",
		"auth_groups.description",
	}
}

// Joins returns a slice of join expressions for [AuthGroupsRow].
func (a AuthGroupsRow) Joins() []string {
	return []string{}
}

// ScanArgs implements [query.ScanArger] for [AuthGroupsRow].
// This returns references to struct fields in definition order.
func (a *AuthGroupsRow) ScanArgs() []any {
	return []any{&a.ID, &a.Name, &a.Description}
}

// CreateValues returns a list of values from [AuthGroupsRow] entities matching the bind arguments in [CreateStmt].
func (a AuthGroupsRow) CreateValues() []any {
	return []any{a.Name, a.Description}
}

// UpdateValues returns a list of values from [AuthGroupsRow] entities matching the columns in [UpdateStmt].
func (a AuthGroupsRow) UpdateValues() []any {
	return []any{a.Name, a.Description}
}

// PKColumn returns the column name for the primary key of a [AuthGroupsRow] entity used during an update.
func (a AuthGroupsRow) PKColumn() string {
	return "id"
}

// PKValue returns the value for the primary key of a [AuthGroupsRow] entity used during an update.
func (a AuthGroupsRow) PKValue() any {
	return a.ID
}

// CreateStmt returns a query that creates a [AuthGroupsRow] entity.
func (a AuthGroupsRow) CreateStmt() string {
	return "INSERT INTO auth_groups (name, description) VALUES (?, ?)"
}

// UpdateStmt returns a query that updates a [AuthGroupsRow] by primary key.
func (a AuthGroupsRow) UpdateStmt() string {
	return "UPDATE auth_groups SET name = ?, description = ? "
}

// TableName returns the table name for [CertificatesRow] entities.
func (c CertificatesRow) TableName() string {
	return "certificates"
}

// SelectColumns returns a slice of column names for [CertificatesRow] entities.
func (c CertificatesRow) SelectColumns() []string {
	return []string{
		"certificates.id",
		"certificates.fingerprint",
		"certificates.certificate",
		"certificates.creation_date",
	}
}

// Joins returns a slice of join expressions for [CertificatesRow].
func (c CertificatesRow) Joins() []string {
	return []string{}
}

// ScanArgs implements [query.ScanArger] for [CertificatesRow].
// This returns references to struct fields in definition order.
func (c *CertificatesRow) ScanArgs() []any {
	return []any{&c.ID, &c.Fingerprint, &c.Certificate, &c.CreationDate}
}

// CreateValues returns a list of values from [CertificatesRow] entities matching the bind arguments in [CreateStmt].
func (c CertificatesRow) CreateValues() []any {
	return []any{c.Fingerprint, c.Certificate}
}

// UpdateValues returns a list of values from [CertificatesRow] entities matching the columns in [UpdateStmt].
func (c CertificatesRow) UpdateValues() []any {
	return []any{c.Fingerprint, c.Certificate}
}

// PKColumn returns the column name for the primary key of a [CertificatesRow] entity used during an update.
func (c CertificatesRow) PKColumn() string {
	return "id"
}

// PKValue returns the value for the primary key of a [CertificatesRow] entity used during an update.
func (c CertificatesRow) PKValue() any {
	return c.ID
}

// CreateStmt returns a query that creates a [CertificatesRow] entity.
func (c CertificatesRow) CreateStmt() string {
	return "INSERT INTO certificates (fingerprint, certificate) VALUES (?, ?)"
}

// UpdateStmt returns a query that updates a [CertificatesRow] by primary key.
func (c CertificatesRow) UpdateStmt() string {
	return "UPDATE certificates SET fingerprint = ?, certificate = ? "
}

// TableName returns the table name for [ClusterLinkRow] entities.
func (c ClusterLinkRow) TableName() string {
	return "cluster_links"
}

// SelectColumns returns a slice of column names for [ClusterLinkRow] entities.
func (c ClusterLinkRow) SelectColumns() []string {
	return []string{
		"cluster_links.id",
		"cluster_links.identity_id",
		"cluster_links.name",
		"cluster_links.description",
		"cluster_links.type",
	}
}

// Joins returns a slice of join expressions for [ClusterLinkRow].
func (c ClusterLinkRow) Joins() []string {
	return []string{}
}

// ScanArgs implements [query.ScanArger] for [ClusterLinkRow].
// This returns references to struct fields in definition order.
func (c *ClusterLinkRow) ScanArgs() []any {
	return []any{&c.ID, &c.IdentityID, &c.Name, &c.Description, &c.Type}
}

// CreateValues returns a list of values from [ClusterLinkRow] entities matching the bind arguments in [CreateStmt].
func (c ClusterLinkRow) CreateValues() []any {
	return []any{c.IdentityID, c.Name, c.Description, c.Type}
}

// UpdateValues returns a list of values from [ClusterLinkRow] entities matching the columns in [UpdateStmt].
func (c ClusterLinkRow) UpdateValues() []any {
	return []any{c.IdentityID, c.Name, c.Description, c.Type}
}

// PKColumn returns the column name for the primary key of a [ClusterLinkRow] entity used during an update.
func (c ClusterLinkRow) PKColumn() string {
	return "id"
}

// PKValue returns the value for the primary key of a [ClusterLinkRow] entity used during an update.
func (c ClusterLinkRow) PKValue() any {
	return c.ID
}

// CreateStmt returns a query that creates a [ClusterLinkRow] entity.
func (c ClusterLinkRow) CreateStmt() string {
	return "INSERT INTO cluster_links (identity_id, name, description, type) VALUES (?, ?, ?, ?)"
}

// UpdateStmt returns a query that updates a [ClusterLinkRow] by primary key.
func (c ClusterLinkRow) UpdateStmt() string {
	return "UPDATE cluster_links SET identity_id = ?, name = ?, description = ?, type = ? "
}

// TableName returns the table name for [IdentitiesRow] entities.
func (i IdentitiesRow) TableName() string {
	return "identities"
}

// SelectColumns returns a slice of column names for [IdentitiesRow] entities.
func (i IdentitiesRow) SelectColumns() []string {
	return []string{
		"identities.id",
		"identities.auth_method",
		"identities.type",
		"identities.identifier",
		"identities.name",
		"identities.metadata",
	}
}

// Joins returns a slice of join expressions for [IdentitiesRow].
func (i IdentitiesRow) Joins() []string {
	return []string{}
}

// ScanArgs implements [query.ScanArger] for [IdentitiesRow].
// This returns references to struct fields in definition order.
func (i *IdentitiesRow) ScanArgs() []any {
	return []any{&i.ID, &i.AuthMethod, &i.Type, &i.Identifier, &i.Name, &i.Metadata}
}

// CreateValues returns a list of values from [IdentitiesRow] entities matching the bind arguments in [CreateStmt].
func (i IdentitiesRow) CreateValues() []any {
	return []any{i.AuthMethod, i.Type, i.Identifier, i.Name, i.Metadata}
}

// UpdateValues returns a list of values from [IdentitiesRow] entities matching the columns in [UpdateStmt].
func (i IdentitiesRow) UpdateValues() []any {
	return []any{i.AuthMethod, i.Type, i.Identifier, i.Name, i.Metadata}
}

// PKColumn returns the column name for the primary key of a [IdentitiesRow] entity used during an update.
func (i IdentitiesRow) PKColumn() string {
	return "id"
}

// PKValue returns the value for the primary key of a [IdentitiesRow] entity used during an update.
func (i IdentitiesRow) PKValue() any {
	return i.ID
}

// CreateStmt returns a query that creates a [IdentitiesRow] entity.
func (i IdentitiesRow) CreateStmt() string {
	return "INSERT INTO identities (auth_method, type, identifier, name, metadata) VALUES (?, ?, ?, ?, ?)"
}

// UpdateStmt returns a query that updates a [IdentitiesRow] by primary key.
func (i IdentitiesRow) UpdateStmt() string {
	return "UPDATE identities SET auth_method = ?, type = ?, identifier = ?, name = ?, metadata = ? "
}

// TableName returns the table name for [IdentityCertificate] entities.
func (i IdentityCertificate) TableName() string {
	return "certificates"
}

// APIName implements [query.APINamer] for API friendly error messages.
func (i IdentityCertificate) APIName() string {
	return i.Row.APIName()
}

// SelectColumns returns a slice of column names for [IdentityCertificate] entities.
func (i IdentityCertificate) SelectColumns() []string {
	return []string{
		"certificates.id",
		"certificates.fingerprint",
		"certificates.certificate",
		"certificates.creation_date",
		"identities_certificates.identity_id",
	}
}

// Joins returns a slice of join expressions for [IdentityCertificate].
func (i IdentityCertificate) Joins() []string {
	return []string{
		"JOIN identities_certificates ON certificates.id = identities_certificates.certificate_id",
	}
}

// ScanArgs implements [query.ScanArger] for [IdentityCertificate].
// This returns references to struct fields in definition order.
func (i *IdentityCertificate) ScanArgs() []any {
	return []any{&i.Row.ID, &i.Row.Fingerprint, &i.Row.Certificate, &i.Row.CreationDate, &i.IdentityID}
}

// TableName returns the table name for [NetworksLoadBalancersPool] entities.
func (n NetworksLoadBalancersPool) TableName() string {
	return "networks_load_balancers_pools"
}

// APIName implements [query.APINamer] for API friendly error messages.
func (n NetworksLoadBalancersPool) APIName() string {
	return n.Row.APIName()
}

// SelectColumns returns a slice of column names for [NetworksLoadBalancersPool] entities.
func (n NetworksLoadBalancersPool) SelectColumns() []string {
	return []string{
		"networks_load_balancers_pools.id",
		"networks_load_balancers_pools.network_id",
		"networks_load_balancers_pools.name",
		"networks_load_balancers_pools.description",
		"networks.name",
		"projects.name",
	}
}

// Joins returns a slice of join expressions for [NetworksLoadBalancersPool].
func (n NetworksLoadBalancersPool) Joins() []string {
	return []string{
		"JOIN networks ON networks.id = networks_load_balancers_pools.network_id",
		"JOIN projects ON projects.id = networks.project_id",
	}
}

// ScanArgs implements [query.ScanArger] for [NetworksLoadBalancersPool].
// This returns references to struct fields in definition order.
func (n *NetworksLoadBalancersPool) ScanArgs() []any {
	return []any{&n.Row.ID, &n.Row.NetworkID, &n.Row.Name, &n.Row.Description, &n.NetworkName, &n.ProjectName}
}

// TableName returns the table name for [NetworksLoadBalancersPoolInstance] entities.
func (n NetworksLoadBalancersPoolInstance) TableName() string {
	return "networks_load_balancers_pools_instances"
}

// APIName implements [query.APINamer] for API friendly error messages.
func (n NetworksLoadBalancersPoolInstance) APIName() string {
	return n.Row.APIName()
}

// SelectColumns returns a slice of column names for [NetworksLoadBalancersPoolInstance] entities.
func (n NetworksLoadBalancersPoolInstance) SelectColumns() []string {
	return []string{
		"networks_load_balancers_pools_instances.id",
		"networks_load_balancers_pools_instances.network_load_balancer_pool_id",
		"networks_load_balancers_pools_instances.instance_id",
		"networks_load_balancers_pools_instances.target_port",
		"instances.name",
	}
}

// Joins returns a slice of join expressions for [NetworksLoadBalancersPoolInstance].
func (n NetworksLoadBalancersPoolInstance) Joins() []string {
	return []string{
		"JOIN instances ON instances.id = networks_load_balancers_pools_instances.instance_id",
	}
}

// ScanArgs implements [query.ScanArger] for [NetworksLoadBalancersPoolInstance].
// This returns references to struct fields in definition order.
func (n *NetworksLoadBalancersPoolInstance) ScanArgs() []any {
	return []any{&n.Row.ID, &n.Row.PoolID, &n.Row.InstanceID, &n.Row.TargetPort, &n.InstanceName}
}

// TableName returns the table name for [NetworksLoadBalancersPoolInstanceRow] entities.
func (n NetworksLoadBalancersPoolInstanceRow) TableName() string {
	return "networks_load_balancers_pools_instances"
}

// SelectColumns returns a slice of column names for [NetworksLoadBalancersPoolInstanceRow] entities.
func (n NetworksLoadBalancersPoolInstanceRow) SelectColumns() []string {
	return []string{
		"networks_load_balancers_pools_instances.id",
		"networks_load_balancers_pools_instances.network_load_balancer_pool_id",
		"networks_load_balancers_pools_instances.instance_id",
		"networks_load_balancers_pools_instances.target_port",
	}
}

// Joins returns a slice of join expressions for [NetworksLoadBalancersPoolInstanceRow].
func (n NetworksLoadBalancersPoolInstanceRow) Joins() []string {
	return []string{}
}

// ScanArgs implements [query.ScanArger] for [NetworksLoadBalancersPoolInstanceRow].
// This returns references to struct fields in definition order.
func (n *NetworksLoadBalancersPoolInstanceRow) ScanArgs() []any {
	return []any{&n.ID, &n.PoolID, &n.InstanceID, &n.TargetPort}
}

// CreateValues returns a list of values from [NetworksLoadBalancersPoolInstanceRow] entities matching the bind arguments in [CreateStmt].
func (n NetworksLoadBalancersPoolInstanceRow) CreateValues() []any {
	return []any{n.PoolID, n.InstanceID, n.TargetPort}
}

// UpdateValues returns a list of values from [NetworksLoadBalancersPoolInstanceRow] entities matching the columns in [UpdateStmt].
func (n NetworksLoadBalancersPoolInstanceRow) UpdateValues() []any {
	return []any{n.PoolID, n.InstanceID, n.TargetPort}
}

// PKColumn returns the column name for the primary key of a [NetworksLoadBalancersPoolInstanceRow] entity used during an update.
func (n NetworksLoadBalancersPoolInstanceRow) PKColumn() string {
	return "id"
}

// PKValue returns the value for the primary key of a [NetworksLoadBalancersPoolInstanceRow] entity used during an update.
func (n NetworksLoadBalancersPoolInstanceRow) PKValue() any {
	return n.ID
}

// CreateStmt returns a query that creates a [NetworksLoadBalancersPoolInstanceRow] entity.
func (n NetworksLoadBalancersPoolInstanceRow) CreateStmt() string {
	return "INSERT INTO networks_load_balancers_pools_instances (network_load_balancer_pool_id, instance_id, target_port) VALUES (?, ?, ?)"
}

// UpdateStmt returns a query that updates a [NetworksLoadBalancersPoolInstanceRow] by primary key.
func (n NetworksLoadBalancersPoolInstanceRow) UpdateStmt() string {
	return "UPDATE networks_load_balancers_pools_instances SET network_load_balancer_pool_id = ?, instance_id = ?, target_port = ? "
}

// TableName returns the table name for [NetworksLoadBalancersPoolRow] entities.
func (n NetworksLoadBalancersPoolRow) TableName() string {
	return "networks_load_balancers_pools"
}

// SelectColumns returns a slice of column names for [NetworksLoadBalancersPoolRow] entities.
func (n NetworksLoadBalancersPoolRow) SelectColumns() []string {
	return []string{
		"networks_load_balancers_pools.id",
		"networks_load_balancers_pools.network_id",
		"networks_load_balancers_pools.name",
		"networks_load_balancers_pools.description",
	}
}

// Joins returns a slice of join expressions for [NetworksLoadBalancersPoolRow].
func (n NetworksLoadBalancersPoolRow) Joins() []string {
	return []string{}
}

// ScanArgs implements [query.ScanArger] for [NetworksLoadBalancersPoolRow].
// This returns references to struct fields in definition order.
func (n *NetworksLoadBalancersPoolRow) ScanArgs() []any {
	return []any{&n.ID, &n.NetworkID, &n.Name, &n.Description}
}

// CreateValues returns a list of values from [NetworksLoadBalancersPoolRow] entities matching the bind arguments in [CreateStmt].
func (n NetworksLoadBalancersPoolRow) CreateValues() []any {
	return []any{n.NetworkID, n.Name, n.Description}
}

// UpdateValues returns a list of values from [NetworksLoadBalancersPoolRow] entities matching the columns in [UpdateStmt].
func (n NetworksLoadBalancersPoolRow) UpdateValues() []any {
	return []any{n.NetworkID, n.Name, n.Description}
}

// PKColumn returns the column name for the primary key of a [NetworksLoadBalancersPoolRow] entity used during an update.
func (n NetworksLoadBalancersPoolRow) PKColumn() string {
	return "id"
}

// PKValue returns the value for the primary key of a [NetworksLoadBalancersPoolRow] entity used during an update.
func (n NetworksLoadBalancersPoolRow) PKValue() any {
	return n.ID
}

// CreateStmt returns a query that creates a [NetworksLoadBalancersPoolRow] entity.
func (n NetworksLoadBalancersPoolRow) CreateStmt() string {
	return "INSERT INTO networks_load_balancers_pools (network_id, name, description) VALUES (?, ?, ?)"
}

// UpdateStmt returns a query that updates a [NetworksLoadBalancersPoolRow] by primary key.
func (n NetworksLoadBalancersPoolRow) UpdateStmt() string {
	return "UPDATE networks_load_balancers_pools SET network_id = ?, name = ?, description = ? "
}

// TableName returns the table name for [PlacementGroup] entities.
func (p PlacementGroup) TableName() string {
	return "placement_groups"
}

// APIName implements [query.APINamer] for API friendly error messages.
func (p PlacementGroup) APIName() string {
	return p.Row.APIName()
}

// SelectColumns returns a slice of column names for [PlacementGroup] entities.
func (p PlacementGroup) SelectColumns() []string {
	return []string{
		"placement_groups.id",
		"placement_groups.name",
		"placement_groups.description",
		"placement_groups.project_id",
		"projects.name",
	}
}

// Joins returns a slice of join expressions for [PlacementGroup].
func (p PlacementGroup) Joins() []string {
	return []string{
		"JOIN projects ON placement_groups.project_id = projects.id",
	}
}

// ScanArgs implements [query.ScanArger] for [PlacementGroup].
// This returns references to struct fields in definition order.
func (p *PlacementGroup) ScanArgs() []any {
	return []any{&p.Row.ID, &p.Row.Name, &p.Row.Description, &p.Row.ProjectID, &p.ProjectName}
}

// TableName returns the table name for [PlacementGroupsRow] entities.
func (p PlacementGroupsRow) TableName() string {
	return "placement_groups"
}

// SelectColumns returns a slice of column names for [PlacementGroupsRow] entities.
func (p PlacementGroupsRow) SelectColumns() []string {
	return []string{
		"placement_groups.id",
		"placement_groups.name",
		"placement_groups.description",
		"placement_groups.project_id",
	}
}

// Joins returns a slice of join expressions for [PlacementGroupsRow].
func (p PlacementGroupsRow) Joins() []string {
	return []string{}
}

// ScanArgs implements [query.ScanArger] for [PlacementGroupsRow].
// This returns references to struct fields in definition order.
func (p *PlacementGroupsRow) ScanArgs() []any {
	return []any{&p.ID, &p.Name, &p.Description, &p.ProjectID}
}

// CreateValues returns a list of values from [PlacementGroupsRow] entities matching the bind arguments in [CreateStmt].
func (p PlacementGroupsRow) CreateValues() []any {
	return []any{p.Name, p.Description, p.ProjectID}
}

// UpdateValues returns a list of values from [PlacementGroupsRow] entities matching the columns in [UpdateStmt].
func (p PlacementGroupsRow) UpdateValues() []any {
	return []any{p.Name, p.Description, p.ProjectID}
}

// PKColumn returns the column name for the primary key of a [PlacementGroupsRow] entity used during an update.
func (p PlacementGroupsRow) PKColumn() string {
	return "id"
}

// PKValue returns the value for the primary key of a [PlacementGroupsRow] entity used during an update.
func (p PlacementGroupsRow) PKValue() any {
	return p.ID
}

// CreateStmt returns a query that creates a [PlacementGroupsRow] entity.
func (p PlacementGroupsRow) CreateStmt() string {
	return "INSERT INTO placement_groups (name, description, project_id) VALUES (?, ?, ?)"
}

// UpdateStmt returns a query that updates a [PlacementGroupsRow] by primary key.
func (p PlacementGroupsRow) UpdateStmt() string {
	return "UPDATE placement_groups SET name = ?, description = ?, project_id = ? "
}

// TableName returns the table name for [Replicator] entities.
func (r Replicator) TableName() string {
	return "replicators"
}

// APIName implements [query.APINamer] for API friendly error messages.
func (r Replicator) APIName() string {
	return r.Row.APIName()
}

// SelectColumns returns a slice of column names for [Replicator] entities.
func (r Replicator) SelectColumns() []string {
	return []string{
		"replicators.id",
		"replicators.name",
		"replicators.project_id",
		"replicators.description",
		"replicators.last_run_date",
		"replicators.last_run_status",
		"projects.name",
	}
}

// Joins returns a slice of join expressions for [Replicator].
func (r Replicator) Joins() []string {
	return []string{
		"JOIN projects ON replicators.project_id = projects.id",
	}
}

// ScanArgs implements [query.ScanArger] for [Replicator].
// This returns references to struct fields in definition order.
func (r *Replicator) ScanArgs() []any {
	return []any{&r.Row.ID, &r.Row.Name, &r.Row.ProjectID, &r.Row.Description, &r.Row.LastRunDate, &r.Row.LastRunStatus, &r.ProjectName}
}

// TableName returns the table name for [ReplicatorRow] entities.
func (r ReplicatorRow) TableName() string {
	return "replicators"
}

// SelectColumns returns a slice of column names for [ReplicatorRow] entities.
func (r ReplicatorRow) SelectColumns() []string {
	return []string{
		"replicators.id",
		"replicators.name",
		"replicators.project_id",
		"replicators.description",
		"replicators.last_run_date",
		"replicators.last_run_status",
	}
}

// Joins returns a slice of join expressions for [ReplicatorRow].
func (r ReplicatorRow) Joins() []string {
	return []string{}
}

// ScanArgs implements [query.ScanArger] for [ReplicatorRow].
// This returns references to struct fields in definition order.
func (r *ReplicatorRow) ScanArgs() []any {
	return []any{&r.ID, &r.Name, &r.ProjectID, &r.Description, &r.LastRunDate, &r.LastRunStatus}
}

// CreateValues returns a list of values from [ReplicatorRow] entities matching the bind arguments in [CreateStmt].
func (r ReplicatorRow) CreateValues() []any {
	return []any{r.Name, r.ProjectID, r.Description, r.LastRunDate, r.LastRunStatus}
}

// UpdateValues returns a list of values from [ReplicatorRow] entities matching the columns in [UpdateStmt].
func (r ReplicatorRow) UpdateValues() []any {
	return []any{r.Name, r.ProjectID, r.Description, r.LastRunDate, r.LastRunStatus}
}

// PKColumn returns the column name for the primary key of a [ReplicatorRow] entity used during an update.
func (r ReplicatorRow) PKColumn() string {
	return "id"
}

// PKValue returns the value for the primary key of a [ReplicatorRow] entity used during an update.
func (r ReplicatorRow) PKValue() any {
	return r.ID
}

// CreateStmt returns a query that creates a [ReplicatorRow] entity.
func (r ReplicatorRow) CreateStmt() string {
	return "INSERT INTO replicators (name, project_id, description, last_run_date, last_run_status) VALUES (?, ?, ?, ?, ?)"
}

// UpdateStmt returns a query that updates a [ReplicatorRow] by primary key.
func (r ReplicatorRow) UpdateStmt() string {
	return "UPDATE replicators SET name = ?, project_id = ?, description = ?, last_run_date = ?, last_run_status = ? "
}
